name: Format & Lint

on: [pull_request, workflow_call]

jobs:
    lint:
        name: Check formatting and linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: hashicorp/setup-terraform@v2

            - name: Run terraform fmt
              run: terraform fmt -check -recursive

            - uses: actions/cache@v3
              name: Cache plugin dir
              with:
                  path: ~/.tflint.d/plugins
                  key: tflint-${{ hashFiles('.tflint.hcl') }}

            - uses: terraform-linters/setup-tflint@v3
              name: Setup TFLint
              with:
                tflint_version: v0.44.1

            - name: Show version
              run: tflint --version

            - name: Init TFLint
              run: tflint --init
              env:
                  GITHUB_TOKEN: ${{ github.token }}

            - name: Run TFLint
              run: tflint --config "$(pwd)/.tflint.hcl" --recursive
